import Head from "next/head";
import { Inter } from "next/font/google";
import { useRouter } from "next/router";
import Present from "./present";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();

  const [color, setColor] = useState("salon");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={
          color === "clinic"
            ? "main clinic"
            : color === "salon"
            ? "main salon"
            : color === "barber"
            ? "main barber"
            : "main"
        }
      >
        <Present />
      </main>
    </>
  );
}
